import assert from 'node:assert/strict';import worker from './_worker.js';import {D1Local} from './TOYO8-d1-local.mjs';
const env={DB:new D1Local(),STORE_DB:new D1Local(),STORE_OWNER_EMAIL:'owner@example.invalid',STORE_SETUP_SECRET:'fictional-local-test-secret-only'},origin='https://requests.test';let checks=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++},password='Fictional local test phrase 2026';
async function call(path,{s,body,method=body?'POST':'GET',headers={}}={}){const r=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':crypto.randomUUID(),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')}}
const session=r=>({cookie:r.cookie.split(';')[0],csrf:r.data.csrf}),admin=session(await call('store/bootstrap',{body:{email:env.STORE_OWNER_EMAIL,secret:env.STORE_SETUP_SECRET,name:'Fixture',password}}));
const roles={admin};for(const role of ['gerente','compras','vendedor','bodega','contabilidad']){const invite=await call('store/invites',{s:admin,body:{email:role+'@example.invalid',role}});const result=await call('store/accept-invite',{body:{token:invite.data.url.split('#')[1],name:role,password}});roles[role]=session(result);eq(result.data.views.includes('suppliers'),['gerente','compras'].includes(role),'role-specific supplier module '+role)}
eq((await call('store/supplier-directory')).status,401,'anonymous directory blocked');
const demo=session(await call('login',{body:{username:'admin',password:'demo123'}}));eq((await call('store/supplier-directory',{s:demo})).status,401,'demo cannot get real directory');
for(const [role,s]of Object.entries(roles)){const result=await call('store/supplier-directory',{s});eq(result.status,['admin','gerente','compras'].includes(role)?200:403,'directory backend authorization '+role)}
const offer={proveedor:'CONFIDENTIAL TEST SUPPLIER',referencia:'PART-123',nombre:'Pieza ficticia',marca:'Toyota',stock_proveedor:8,precio_cop:40000,plazo_dias:3,actualizado:new Date().toISOString().slice(0,10),mostrar_cliente:true,precio_venta_cop:90000};eq((await call('store/offers/import',{s:admin,body:{rows:[offer]}})).status,200,'old publication flag cannot expose offer');
for(const [role,s]of Object.entries(roles)){const state=(await call('store/state',{s})).data;eq(state.offers.length,['admin','gerente','compras'].includes(role)?1:0,'private offers role '+role)}
const customer=session(await call('customer/register',{body:{email:'one@example.invalid',name:'Customer One',password,consent:true}})),other=session(await call('customer/register',{body:{email:'two@example.invalid',name:'Customer Two',password,consent:true}}));
for(const s of [undefined,customer,admin]){const result=(await call('catalog?q=PART-123',{s})).data;eq(result.offers,[],'no supplier response even with staff cookie');eq(JSON.stringify(result).includes(offer.proveedor),false,'no provider identity leak')}
eq((await call('store/supplier-directory',{s:customer})).status,401,'customer no staff directory');eq((await call('customer/part-requests')).status,401,'request needs customer session');eq((await call('customer/part-requests',{s:admin})).status,401,'staff cannot impersonate customer');
const request={part:'Filtro <script>test</script>',reference:'PART-123',brand:'Toyota',qty:1,notes:'Prueba local',consent:true,status:'revisada',estimatedDays:3,supplier:'spoof'};
eq((await call('customer/part-requests',{s:customer,body:{...request,consent:false}})).status,400,'explicit request consent');eq((await call('customer/part-requests',{s:{...customer,csrf:'wrong'},body:request})).status,403,'request CSRF');eq((await call('customer/part-requests',{s:customer,body:request,headers:{Origin:'https://evil.invalid'}})).status,403,'request origin');
const vehicle=(await call('customer/vehicles',{s:customer,body:{plate:'ZZZ999',brand:'Toyota',model:'Fictional model',vin:'',chassis:''}})).data;
eq((await call('customer/part-requests',{s:other,body:{...request,vehicleId:vehicle.id}})).status,404,'cross-customer vehicle rejected');
const created=await call('customer/part-requests',{s:customer,body:{...request,vehicleId:vehicle.id}});eq(created.status,201,'request persisted');eq(created.data.status,'pendiente','customer cannot set result');eq(created.data.estimatedDays,null,'no invented ETA');eq('supplier' in created.data,false,'supplier spoof ignored');
eq((await call('customer/part-requests',{s:other})).data.requests.length,0,'request account isolation');eq((await call('customer/part-requests',{s:customer})).data.requests.length,1,'owner gets own request');
const state=(await call('store/state',{s:admin})).data,record=state.requests[0];eq(record.email,'one@example.invalid','known customer identity');eq(record.vehicle.plate,'ZZZ999','only owned selected vehicle');eq((await call('store/state',{s:roles.compras})).data.requests.length,0,'purchasing does not get contacts');
eq((await call('store/requests/respond',{s:roles.compras,body:{id:record.id,version:record.version,status:'revisada',days:3,confirmed:true,reply:'Llegará en tres días'}})).status,403,'purchasing cannot publish customer reply');
eq((await call('store/requests/respond',{s:admin,body:{id:record.id,version:record.version,status:'revisada',days:3,confirmed:false,reply:'Plazo estimado'}})).status,400,'must confirm ETA');
eq((await call('store/requests/respond',{s:admin,body:{id:record.id,version:record.version,status:'revisada',days:3,confirmed:true,reply:'Podemos solicitarla. Llegada estimada al local: 3 días desde confirmar el pedido.',supplier:'leak',cost:40000}})).status,200,'staff publishes approved estimate');
const result=(await call('customer/part-requests',{s:customer})).data.requests[0];eq(result.estimatedDays,3,'confirmed three day estimate');eq(result.status,'revisada','client sees progress');eq('cost' in result,false,'no provider cost in response');eq('supplier' in result,false,'no provider in response');eq((await call('customer/part-requests',{s:other})).data.requests.length,0,'reply private to customer');
eq((await call('store/requests/respond',{s:admin,body:{id:record.id,version:record.version,status:'cerrada',days:null,reply:'stale'}})).status,409,'optimistic version prevents lost reply');
eq((await call('customer/export',{s:customer})).data.requests.length,1,'private account export includes requests');
eq((await call('customer/delete-account',{s:customer,body:{email:'one@example.invalid',password,confirm:true}})).status,200,'delete account');eq((await call('store/state',{s:admin})).data.requests.length,0,'account request purged');
console.log(JSON.stringify({passed:checks,flows:['supplier authorization','no public source or price leak','registered requests','consent/CSRF/origin','vehicle/customer isolation','manual confirmed ETA','version conflict','export/deletion']}));
