import assert from 'node:assert/strict';import worker from './_worker.js';import {D1Local} from './TOYO8-d1-local.mjs';
const DB=new D1Local(),env={DB},origin='https://garage.test';let checks=0;
const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++};
async function call(path,{method='GET',body,s,headers={}}={},runner=worker){const r=await runner.fetch(new Request(origin+'/api/'+path,{method,headers:{...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'}),'CF-Connecting-IP':'garage-'+crypto.randomUUID(),...headers,...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')}}
const password='Una frase ficticia de prueba 2026';
async function register(email,name='Cliente ficticio'){const r=await call('customer/register',{method:'POST',body:{email,name,password,consent:true}});eq(r.status,200,'account created');assert.match(r.cookie,/HttpOnly; Secure; SameSite=Strict/);checks++;return {cookie:r.cookie.split(';')[0],csrf:r.data.csrf,email}}
async function login(email){const r=await call('customer/login',{method:'POST',body:{email,password}});eq(r.status,200,'customer login');return {cookie:r.cookie.split(';')[0],csrf:r.data.csrf,email}}
eq((await call('customer/vehicles')).status,401,'anonymous vehicles blocked');
eq((await call('customer/register',{method:'POST',body:{email:'a@example.invalid',name:'Ficticio',password,consent:false}})).status,400,'registration requires consent');
eq((await call('customer/register',{method:'POST',body:{email:'a@example.invalid',name:'Ficticio',password:'short',consent:true}})).status,400,'weak password rejected');
const a=await register('A@example.invalid'),b=await register('b@example.invalid');
const me=(await call('customer/me',{s:a})).data;eq(me.email,'a@example.invalid','email normalized');eq('password'in me||'salt'in me||'id'in me,false,'credential material never returned');
eq((await call('customer/register',{method:'POST',body:{email:a.email,name:'Duplicate',password,consent:true}})).status,409,'duplicate account rejected');
eq((await call('customer/login',{method:'POST',body:{email:a.email,password:'Wrong password'}})).status,401,'wrong password rejected');
eq((await call('customer/login',{method:'POST',body:{email:'absent@example.invalid',password:'Wrong password'}})).data.error,'Correo o clave incorrectos.','missing account has same error');
const data={plate:'abc-123',vin:'1HGCM82633A004352',chassis:'',brand:'Marca ficticia',model:'Modelo ficticio',year:2003,engine:'Motor ficticio',color:'Blanco',compatibility:'verified',owner:b.email};
eq((await call('customer/vehicles',{method:'POST',body:data,s:{...a,csrf:'wrong'}})).status,403,'CSRF enforced');
eq((await call('customer/vehicles',{method:'POST',body:{...data,vin:'INVALID'},s:a})).status,400,'invalid VIN blocked');
const created=await call('customer/vehicles',{method:'POST',body:data,s:a});eq(created.status,201,'vehicle persisted');const v=created.data;eq(v.plate,'ABC123','plate normalized');eq(v.compatibility,'pending','browser cannot assert compatibility');eq('owner'in v,false,'browser ownership ignored');
eq((await call('customer/vehicles',{s:a})).data.vehicles.length,1,'private garage retrieves vehicle');eq((await call('customer/vehicles',{s:b})).data.vehicles.length,0,'separate customer garage');
eq((await call('customer/vehicles',{method:'POST',body:data,s:a})).status,409,'duplicate identifier rejected');
eq((await call('customer/vehicles',{method:'PATCH',body:{...data,id:v.id,version:1},s:b})).status,409,'cross account update blocked');
let edit=await call('customer/vehicles',{method:'PATCH',body:{...data,id:v.id,version:1,color:'Negro'},s:a});eq(edit.status,200,'owned vehicle edited');eq(edit.data.version,2,'version updated');eq((await call('customer/vehicles',{method:'PATCH',body:{...data,id:v.id,version:1,color:'Rojo'},s:a})).status,409,'stale edit rejected');
const legacy=await call('customer/vehicles',{method:'POST',body:{plate:'DEF456',vin:'',chassis:'R1126-12345',brand:'Marca ficticia',model:'Vehículo antiguo',year:1978},s:a});eq(legacy.status,201,'legacy chassis saved without fabricated VIN');
eq((await call('stock',{method:'POST',s:a,body:{role:'admin',id:'pieza-demo-1',version:1,delta:1,reason:'Attempt'}})).status,401,'customer cannot act as demo staff');
const demo=await call('login',{method:'POST',body:{username:'admin',password:'demo123'}}),demoSession={cookie:demo.cookie.split(';')[0],csrf:demo.data.csrf};eq((await call('customer/vehicles',{s:demoSession})).status,401,'public demo cannot read customers');eq('vehicles'in(await call('state',{s:demoSession})).data,false,'demo state contains no customer records');
const rows=(await DB.prepare('SELECT * FROM tr_customers').all()).results;eq(rows.every(r=>r.password!==password&&r.password.length===64),true,'only derived hashes stored');eq(rows[0].salt!==rows[1].salt,true,'unique per account salt');
eq((await call('customer/logout',{method:'POST',s:a,body:{}})).status,200,'customer logout');eq((await call('customer/vehicles',{s:a})).status,401,'revoked token rejected');
const again=await login('a@example.invalid');eq((await call('customer/vehicles',{s:again})).data.vehicles.length,2,'garage survives logout and login');
const rebooted=(await import('./_worker.js?garage-restart')).default;eq((await call('customer/vehicles',{s:again},rebooted)).data.vehicles.find(p=>p.id===v.id).color,'Negro','garage survives worker restart');
await DB.prepare('UPDATE tr_customer_sessions SET expires=0 WHERE customer=(SELECT id FROM tr_customers WHERE email=?)').bind('b@example.invalid').run();eq((await call('customer/vehicles',{s:b})).status,401,'expired customer session rejected');
const cross=await call('customer/register',{method:'POST',headers:{Origin:'https://other.test'},body:{email:'cross@example.invalid',name:'Ficticio',password,consent:true}});eq(cross.status,403,'foreign origin rejected');
let sent=[];env.VIN_FETCH=async(url,options)=>{sent.push({url,headers:options.headers});return new Response(JSON.stringify({Results:[{Make:'HONDA',Model:'ACCORD',ModelYear:'2003',EngineModel:'K24',DisplacementL:'2.4',FuelTypePrimary:'Gasoline',ErrorCode:'0'}]}),{headers:{'Content-Type':'application/json'}})};
eq((await call('vehicle/decode',{method:'POST',body:{vin:data.vin,consent:false}})).status,400,'external VIN lookup requires consent');eq(sent.length,0,'no lookup without consent');
const decode=await call('vehicle/decode',{method:'POST',body:{vin:data.vin,year:2003,consent:true,plate:'ABC123',email:a.email}});eq(decode.status,200,'documented VIN lookup');eq(decode.data.brand,'HONDA','source fields mapped');eq(decode.data.oem,false,'identification never claims EPC');eq(decode.data.compatibility,'pending','decoder does not verify parts');eq(decode.data.partial,false,'complete decode described');eq(new URL(sent[0].url).hostname,'vpic.nhtsa.dot.gov','lookup only to fixed official host');eq(sent[0].url.includes('ABC123')||sent[0].url.includes(a.email),false,'plate and contact not transmitted');eq(Object.keys(sent[0].headers),['Accept'],'no customer credentials forwarded');
env.VIN_FETCH=async()=>new Response(JSON.stringify({Results:[{Make:'',Model:'',ModelYear:'9999',ErrorCode:'7'}]}));const partial=await call('vehicle/decode',{method:'POST',body:{vin:data.vin,consent:true}});eq(partial.data.partial,true,'partial lookup remains partial');eq(partial.data.brand,'','missing brand not invented');eq(partial.data.year,null,'invalid source year discarded');
env.VIN_FETCH=async()=>{throw Error('Failure '+data.vin)};const offline=await call('vehicle/decode',{method:'POST',body:{vin:data.vin,consent:true}});eq(offline.status,503,'source offline supports manual entry');eq(offline.data.error.includes(data.vin),false,'provider errors do not disclose VIN');
const rateHeaders={'CF-Connecting-IP':'fixed-registration-ip'};for(let n=0;n<5;n++)await call('customer/register',{method:'POST',headers:rateHeaders,body:{email:'rate@example.invalid',name:'Ficticio',password:'short',consent:true}});eq((await call('customer/register',{method:'POST',headers:rateHeaders,body:{email:'rate@example.invalid',name:'Ficticio',password,consent:true}})).status,429,'registration rate limit');
console.log(JSON.stringify({passed:checks,flows:['private registration','derived passwords','cookie security','origin/CSRF','account isolation','owner authorization','persisted vehicles','legacy chassis','duplicate identifiers','optimistic editing','worker restart','logout/expiry','demo separation','VIN consent/minimization','source failures','rate limiting']}));
