import assert from 'node:assert/strict';import worker from './_worker.js';import {D1Local} from './TOYO8-d1-local.mjs';
const DB=new D1Local(),STORE_DB=new D1Local(),env={DB,STORE_DB,STORE_SETUP_SECRET:'local-test-activation-key-only-not-for-production',STORE_OWNER_EMAIL:'owner@example.invalid'},origin='https://store.test';let checks=0;const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++};
async function call(path,{method='GET',body,s,headers={}}={},e=env){const r=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'}),'CF-Connecting-IP':'store-'+crypto.randomUUID(),...headers,...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})}),e);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')}}
const password='Private fictitious test phrase 2026';const session=r=>({cookie:r.cookie.split(';')[0],csrf:r.data.csrf});
eq((await call('store/status',{}, {DB})).data,{database:false,activated:false,setup:false},'missing configuration');eq((await call('store/status',{}, {DB,STORE_DB:DB})).status,503,'same DB refused');eq((await call('store/state')).status,401,'anonymous refused');
eq((await call('store/bootstrap',{method:'POST',body:{secret:env.STORE_SETUP_SECRET,email:env.STORE_OWNER_EMAIL,name:'Test owner',password}},{DB,STORE_DB})).status,503,'setup disabled without secret');
eq((await call('store/bootstrap',{method:'POST',body:{secret:'wrong',email:env.STORE_OWNER_EMAIL,name:'Test owner',password}})).status,403,'invalid setup key');eq((await call('store/bootstrap',{method:'POST',body:{secret:env.STORE_SETUP_SECRET,email:'attacker@example.invalid',name:'Test owner',password}})).status,403,'owner email pinned');
const start=await call('store/bootstrap',{method:'POST',body:{secret:env.STORE_SETUP_SECRET,email:env.STORE_OWNER_EMAIL,name:'Test owner',password}});eq(start.status,200,'owner activated');const admin=session(start);assert.match(start.cookie,/HttpOnly; Secure; SameSite=Strict/);checks++;eq(start.data.mode,'store','real staff mode');eq((await call('store/bootstrap',{method:'POST',body:{secret:env.STORE_SETUP_SECRET,email:env.STORE_OWNER_EMAIL,name:'Again',password}})).status,409,'single owner');eq((await call('store/state',{s:admin})).data.products,[],'empty real store no seed');
const demoResult=await call('login',{method:'POST',body:{username:'admin',password:'demo123'}}),demo=session(demoResult);eq((await call('store/state',{s:demo})).status,401,'demo cannot access store');eq((await call('state',{s:admin})).status,401,'store cookie cannot access demo');
const users={admin};for(const role of ['gerente','vendedor','compras','bodega','contabilidad']){const inv=await call('store/invites',{method:'POST',s:admin,body:{email:role+'@example.invalid',role}});eq(inv.status,201,'invitation '+role);const token=inv.data.url.split('#')[1];const a=await call('store/accept-invite',{method:'POST',body:{token,password,name:role,role:'admin'}});eq(a.status,200,'invitation accepted '+role);eq(a.data.role,role,'spoofing refused '+role);users[role]=session(a);eq((await call('store/accept-invite',{method:'POST',body:{token,password,name:role}})).status,400,'single use '+role);eq((await call('store/invites',{method:'POST',s:users[role],body:{email:'other@example.invalid',role:'admin'}})).status,403,'staff cannot invite '+role)}
eq((await call('store/invites',{method:'POST',s:admin,body:{email:'other@example.invalid',role:'admin'}})).status,400,'no admin promotion');
const product={code:'PART-001',name:'Filtro de prueba <script>bad()</script>',brand:'Test',category:'Motor',location:'A1',price:80000,cost:30000,tax:19,stock:4,min:1,published:true};
eq((await call('store/catalog/import',{method:'POST',s:users.vendedor,body:{rows:[product]}})).status,403,'sales cannot import');eq((await call('store/catalog/import',{method:'POST',s:admin,body:{rows:[product,{...product,code:'PRIVATE-002',published:false}]}})).status,201,'catalogue import');
let publicData=(await call('catalog')).data;eq(publicData.products.length,1,'only published');eq('cost' in publicData.products[0],false,'private cost removed');eq('location' in publicData.products[0],false,'private shelf removed');eq(publicData.products[0].compatibility,'pending','no invented fitment');eq((await call('state',{s:demo})).data.products.some(p=>p.code==='PART-001'),false,'demo isolation');
let state=(await call('store/state',{s:admin})).data,p=state.products.find(p=>p.code==='PART-001');
eq((await call('store/product',{method:'PATCH',s:admin,body:{id:p.id,version:p.version,data:{...p,stock:999,published:true}}})).status,200,'product editing');eq((await call('store/state',{s:admin})).data.products.find(row=>row.id===p.id).stock,4,'editing cannot bypass stock audit');eq((await call('store/product',{method:'PATCH',s:admin,body:{id:p.id,version:p.version,data:p}})).status,409,'optimistic edit');
const offer={proveedor:'Test provider',referencia:'PART-001',nombre:'Filtro',marca:'Test',stock_proveedor:5,precio_cop:35000,precio_venta_cop:90000,plazo_dias:3,actualizado:new Date().toISOString().slice(0,10),mostrar_cliente:true};
eq((await call('store/offers/import',{method:'POST',s:users.compras,body:{rows:[offer]}})).status,200,'procurement import');eq((await call('catalog')).data.offers.length,0,'supplier offers administrative only');eq(JSON.stringify((await call('catalog')).data).includes(offer.proveedor),false,'supplier identity private');eq((await call('store/offers/import',{method:'POST',s:users.compras,body:{rows:[{...offer,proveedor:'Hidden',mostrar_cliente:false}]}})).status,200,'hidden offer import');eq((await call('catalog')).data.offers.length,0,'all supplier offers hidden');eq((await call('store/state',{s:admin})).data.offers.length,2,'merge retains other providers');eq((await call('store/offers/import',{method:'POST',s:users.compras,body:{rows:[{...offer,precio_venta_cop:null}]}})).status,200,'provider offer never requires public price');
for(const role of ['vendedor','bodega','contabilidad']){const d=(await call('store/state',{s:users[role]})).data;eq(d.products.some(p=>'cost' in p),false,'cost privacy '+role);eq(d.offers.some(p=>'cost' in p),false,'offer cost privacy '+role)}
eq((await call('store/state',{s:users.bodega})).data.products.some(p=>'price' in p),false,'warehouse no prices');
const c=await call('store/records',{method:'POST',s:users.vendedor,body:{kind:'clients',data:{name:'Private Test Client',email:'client@example.invalid',phone:'000000',segment:'B2B',discount:10,notes:'Private note'}}});eq(c.status,201,'persistent client');
p=(await call('store/state',{s:admin})).data.products.find(p=>p.code==='PART-001');const q=await call('store/quotes',{method:'POST',s:users.vendedor,body:{clientId:c.data.id,items:[{productId:p.id,qty:1}],notes:'Test quote'}});eq(q.status,201,'real quote');eq(q.data.total,85680,'server B2B tax total');eq(q.data.demo,false,'not demo document');assert.match(q.data.number,/^COT-(?!DEMO)/);checks++;
const order=await call('store/convert',{method:'POST',s:users.vendedor,body:{source:q.data.id,type:'order'}});eq(order.status,201,'real order');eq((await call('store/convert',{method:'POST',s:users.vendedor,body:{source:order.data.id,type:'invoice'}})).status,403,'sales cannot invoice');const sale=await call('store/convert',{method:'POST',s:users.contabilidad,body:{source:order.data.id,type:'invoice'}});eq(sale.status,201,'internal sale');eq((await call('store/convert',{method:'POST',s:users.contabilidad,body:{source:order.data.id,type:'invoice'}})).status,409,'invoice once');eq((await call('store/state',{s:admin})).data.products.find(row=>row.id===p.id).stock,3,'stock once');
eq((await call('store/records',{method:'POST',s:users.vendedor,body:{kind:'clients',data:{name:'Denied'}},headers:{Origin:'https://evil.test'}})).status,403,'origin enforced');eq((await call('store/records',{method:'POST',s:{...admin,csrf:'wrong'},body:{kind:'products',data:product}})).status,403,'CSRF enforced');
eq((await call('store/backup',{s:users.gerente})).status,403,'backup owner only');const backup=await call('store/backup',{s:admin});eq(backup.status,200,'private backup');eq(backup.data.records.some(r=>r.kind==='clients'),true,'backup CRM');eq(JSON.stringify(backup.data).includes(password),false,'no passwords in backup');eq((await call('store/integrations',{s:users.gerente})).data.epc.connected,false,'truthful EPC');eq((await call('store/integrations',{s:users.vendedor})).status,403,'integrations restricted');
const people=await call('store/people',{s:admin});eq(people.data.people.length,6,'six staff');eq(people.data.people.some(p=>'password' in p||'salt' in p),false,'no password hashes in UI');eq((await call('store/people',{s:users.gerente})).status,403,'staff privacy');const salesPerson=people.data.people.find(p=>p.role==='vendedor');eq((await call('store/people',{method:'PATCH',s:admin,body:{id:salesPerson.id,active:false}})).status,200,'deactivation');eq((await call('store/state',{s:users.vendedor})).status,401,'session revoked');eq((await call('store/login',{method:'POST',body:{email:salesPerson.email,password}})).status,401,'inactive cannot login');eq((await call('store/people',{method:'PATCH',s:admin,body:{id:start.data.id,active:false}})).status,409,'cannot remove owner');await call('store/people',{method:'PATCH',s:admin,body:{id:salesPerson.id,active:true}});
const reset=await call('store/invites',{method:'POST',s:admin,body:{email:salesPerson.email,reset:true}});const resetToken=reset.data.url.split('#')[1],newPassword='Another fictional private passphrase 2026';eq((await call('store/accept-invite',{method:'POST',body:{token:resetToken,name:'Ignored rename',password:newPassword}})).status,200,'staff recovery');eq((await call('store/login',{method:'POST',body:{email:salesPerson.email,password}})).status,401,'old password rejected');eq((await call('store/login',{method:'POST',body:{email:salesPerson.email,password:newPassword}})).status,200,'new password accepted');
eq((await call('epc/access')).data.allowed,false,'anonymous no EPC');eq((await call('epc/view')).status,403,'anonymous cannot download viewer');eq((await call('epc/view',{s:demo})).status,403,'demo no EPC');eq((await call('epc/view',{s:admin})).status,200,'owner EPC');for(const role of ['gerente','vendedor','compras','bodega','contabilidad'])eq((await call('epc/access',{s:users[role]})).data.allowed,false,'role alone insufficient '+role);
eq((await call('store/epc-access',{method:'POST',s:users.compras,body:{kind:'staff',email:'compras@example.invalid',enabled:true}})).status,403,'cannot self grant');eq((await call('store/epc-access',{method:'POST',s:admin,body:{kind:'staff',email:'compras@example.invalid',enabled:true}})).status,200,'individual grant');eq((await call('epc/view',{s:users.compras})).status,200,'authorized staff viewer');await call('store/epc-access',{method:'POST',s:admin,body:{kind:'staff',email:'compras@example.invalid',enabled:false}});eq((await call('epc/view',{s:users.compras})).status,403,'revocation enforced immediately');
const customerResult=await call('customer/register',{method:'POST',body:{email:'garage@example.invalid',name:'Garage Test',password,consent:true}}),customerSession=session(customerResult);eq((await call('epc/access',{s:customerSession})).data.allowed,false,'registered client not automatic');eq((await call('store/epc-access',{method:'POST',s:admin,body:{kind:'customer',email:'garage@example.invalid',enabled:true}})).status,400,'customer grants prohibited');eq((await call('epc/view',{s:customerSession})).status,403,'client cannot open administrative viewer');eq((await call('store/state',{s:customerSession})).status,401,'EPC does not grant CRM');await call('store/epc-access',{method:'POST',s:admin,body:{kind:'customer',email:'garage@example.invalid',enabled:false}});eq((await call('epc/view',{s:customerSession})).status,403,'client revoke');const privateCustomer=await env.DB.prepare('SELECT id FROM tr_customers WHERE email=?').bind('garage@example.invalid').first();await env.STORE_DB.prepare('INSERT INTO tr_epc_grants VALUES(?,?,?,1)').bind('customer',privateCustomer.id,'garage@example.invalid').run();eq((await call('epc/view',{s:customerSession})).status,403,'legacy customer grant cannot bypass new policy');eq((await call('store/epc-access',{method:'POST',s:admin,body:{kind:'staff',email:'bodega@example.invalid',enabled:true}})).status,403,'technical operational role not grantable');const warehouseUser=await env.STORE_DB.prepare('SELECT id FROM tr_staff WHERE email=?').bind('bodega@example.invalid').first();await env.STORE_DB.prepare('INSERT INTO tr_epc_grants VALUES(?,?,?,1)').bind('staff',warehouseUser.id,'bodega@example.invalid').run();eq((await call('epc/view',{s:users.bodega})).status,403,'legacy operational grant ignored');eq((await call('store/me',{s:users.bodega})).data.epcAccess,false,'operational profile reflects denial');const runtime=await worker.fetch(new Request(origin+'/api/epc/runtime'),env);eq(runtime.status,403,'runtime cannot be bypassed');eq((await call('store/epc-access',{method:'POST',s:admin,body:{kind:'staff',email:'unknown@example.invalid',enabled:true}})).status,404,'no grant to nonexistent user');

await call('store/logout',{method:'POST',s:admin,body:{}});eq((await call('store/state',{s:admin})).status,401,'logout revokes');const again=await call('store/login',{method:'POST',body:{email:env.STORE_OWNER_EMAIL,password}});eq((await call('store/state',{s:session(again)})).data.clients[0].id,c.data.id,'business data persists across login');
console.log(JSON.stringify({passed:checks,flows:['private database isolation','first owner gating','personal role invitations','token replay','role spoofing','permissions','publication and cost privacy','persistent CRM/B2B/orders/internal sale','stock idempotency','origin/CSRF','backups','deactivation/session revocation','staff recovery','persistent relogin']}));
