import assert from 'node:assert/strict';import worker from './_worker.js';import {D1Local} from './TOYO8-d1-local.mjs';
const env={DB:new D1Local(),STORE_DB:new D1Local(),STORE_OWNER_EMAIL:'owner@example.invalid',STORE_SETUP_SECRET:'only-for-local-fixtures-not-production-key'},origin='https://benefits.test';let checks=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
async function call(path,{body,s,method=body?'POST':'GET'}={}){const r=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{...(body?{Origin:origin,'Content-Type':'application/json'}:{}),'CF-Connecting-IP':crypto.randomUUID(),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')}}
const session=r=>({cookie:r.cookie.split(';')[0],csrf:r.data.csrf}),password='Local fictional phrase test only 2026';
const admin=session(await call('store/bootstrap',{body:{secret:env.STORE_SETUP_SECRET,email:env.STORE_OWNER_EMAIL,name:'Fixture',password}}));const product=(await call('store/records',{s:admin,body:{kind:'products',data:{code:'PAD-TEST',name:'Pastillas ficticias',category:'Pastillas',brand:'Test',price:100001,cost:40000,tax:19,stock:0,min:0,location:'private',published:true}}})).data;
const offer={proveedor:'Test Supplier',referencia:'PAD-TEST',nombre:'Pastillas ficticias',marca:'Test',stock_proveedor:3,precio_cop:30000,precio_venta_cop:150001,plazo_dias:2,actualizado:new Date().toISOString().slice(0,10),mostrar_cliente:true};eq((await call('store/offers/import',{s:admin,body:{rows:[offer]}})).status,200,'offer import');
let d=(await call('catalog')).data;eq(d.membership.eligible,false,'anonymous not member');eq(d.products[0].price,100001,'anonymous base');eq(d.products[0].memberPrice,80001,'rounding discounted pesos');eq(d.offers.length,0,'anonymous never sees suppliers');eq(JSON.stringify(d).includes('Test Supplier'),false,'no provider identity');eq(d.membership.lifetime,true,'lifetime policy');eq((await call('catalog?eligible=true&discount=99')).data.products[0].price,100001,'query spoof ignored');
const customer=session(await call('customer/register',{body:{email:'customer@example.invalid',name:'Test Member',password,consent:true}}));d=(await call('catalog',{s:customer})).data;eq(d.membership.eligible,true,'registered session eligible');eq(d.membership.percent,20,'20 percent');eq(d.products[0].price,80001,'discount server applied');eq(d.products[0].basePrice,100001,'base retained');eq(d.products[0].discount,20000,'discount amount');eq(d.offers.length,0,'membership never discloses suppliers');eq(d.products[0].stock,0,'no fabricated stock');eq((await call('epc/access',{s:customer})).data.allowed,false,'discount does not grant EPC');eq((await call('store/state',{s:customer})).status,401,'discount does not grant staff');
const client=(await call('store/records',{s:admin,body:{kind:'clients',data:{name:'Test',email:'customer@example.invalid',segment:'B2C',discount:0}}})).data;let q=(await call('store/quotes',{s:admin,body:{clientId:client.id,items:[{productId:product.id,qty:2}],discountRate:99}})).data;eq(q.discountRate,20,'private quote derives membership not input');eq(q.discount,40000,'quote discount');eq(q.tax,30400,'tax after discount');eq(q.total,190402,'canonical total');eq(q.memberBenefit,'20 % de por vida para usuarios registrados','benefit in document');
const triple=(await call('store/quotes',{s:admin,body:{clientId:client.id,items:[{productId:product.id,qty:3}]}})).data;eq(triple.items[0].net,80001*3,'unit price and quote quantity agree');
await call('store/records',{s:admin,method:'PATCH',body:{kind:'clients',id:client.id,version:1,data:{discount:25}}});q=(await call('store/quotes',{s:admin,body:{clientId:client.id,items:[{productId:product.id,qty:1}]}})).data;eq(q.discountRate,25,'best discount preserved not stacked');eq(q.discount,25000,'no stacking');
await call('customer/logout',{s:customer,body:{}});eq((await call('catalog',{s:customer})).data.membership.eligible,false,'revoked session loses visible benefit');eq((await call('catalog',{s:customer})).data.products[0].price,100001,'logout reprices');eq((await call('catalog',{s:admin})).data.membership.eligible,false,'staff cookie not customer benefit');
console.log(JSON.stringify({passed:checks,flows:['lifetime membership','server prices and rounding','own stock and supplier offers','no input spoofing','tax and best discount','EPC independent','logout repricing']}));
