import assert from 'node:assert/strict';import worker from './_worker.js';import {D1Local} from './TOYO8-d1-local.mjs';
const env={DB:new D1Local(),STORE_DB:new D1Local(),STORE_OWNER_EMAIL:'owner@example.invalid',STORE_SETUP_SECRET:'fictional-local-test-secret-only'},origin='https://counter.test';let checks=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++},password='Fictional local test phrase 2026';
async function call(path,{s,body,method=body?'POST':'GET',headers={}}={}){const r=await worker.fetch(new Request(origin+'/api/'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':crypto.randomUUID(),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')}}
const session=r=>({cookie:r.cookie.split(';')[0],csrf:r.data.csrf}),admin=session(await call('store/bootstrap',{body:{email:env.STORE_OWNER_EMAIL,secret:env.STORE_SETUP_SECRET,name:'Fixture',password}})),roles={admin};
for(const role of ['gerente','compras','vendedor','bodega','contabilidad']){const invite=await call('store/invites',{s:admin,body:{email:role+'@example.invalid',role}});roles[role]=session(await call('store/accept-invite',{body:{token:invite.data.url.split('#')[1],name:role,password}}));}
const customer=session(await call('customer/register',{body:{email:'customer@example.invalid',name:'Private customer',password,consent:true}})),demo=session(await call('login',{body:{username:'admin',password:'demo123'}}));
for(const s of [undefined,customer,demo])eq((await call('store/vehicles',{s})).status,401,'staff login required');
for(const [role,s]of Object.entries(roles)){eq((await call('store/vehicles',{s})).status,['admin','gerente','vendedor'].includes(role)?200:403,'vehicle role '+role);eq((await call('store/me',{s})).data.views.includes('counter'),['admin','gerente','vendedor'].includes(role),'counter navigation '+role)}
const intake={client:{name:'Fictional visitor',segment:'B2C',email:'visitor@example.invalid',phone:'',discount:0,notes:''},vehicle:{plate:'ZZZ001',vin:'JTEBH3FJ70K123456',chassis:'',brand:'Toyota',model:'Fixture model',year:2018,engine:'Fixture',color:'Gris'},consent:true};
eq((await call('store/intake',{s:admin,body:{...intake,consent:false}})).status,400,'explicit intake consent');eq((await call('store/intake',{s:{...admin,csrf:'wrong'},body:intake})).status,403,'CSRF');eq((await call('store/intake',{s:admin,body:intake,headers:{Origin:'https://evil.invalid'}})).status,403,'origin');eq((await call('store/intake',{s:roles.gerente,body:intake})).status,403,'gerente read only');eq((await call('store/intake',{s:admin,body:{...intake,vehicle:{...intake.vehicle,vin:'bad'}}})).status,400,'VIN validation');
eq((await call('store/state',{s:admin})).data.clients.length,0,'failed intake not partially written');
const first=await call('store/intake',{s:roles.vendedor,body:intake}),v=first.data.vehicle;eq(first.status,201,'atomic client vehicle intake');eq(v.version,1,'initial version');eq(v.compatibility,'pending','VIN does not assert compatibility');eq(v.source,'counter','counter source');eq((await call('store/state',{s:admin})).data.clients.length,1,'one client saved');eq((await call('customer/vehicles',{s:customer})).data.vehicles.length,0,'staff vehicle not in customer private garage');
const duplicate={...intake,client:{...intake.client,email:'other@example.invalid'}};eq((await call('store/intake',{s:admin,body:duplicate})).status,409,'duplicate VIN/plate blocked');eq((await call('store/state',{s:admin})).data.clients.length,1,'duplicate cannot create orphan client');eq((await call('store/intake',{s:admin,body:{...intake,vehicle:{...intake.vehicle,vin:'JTEBH3FJ70K123457',plate:'ZZZ002'}}})).status,409,'existing email asks to reuse client');
const second=await call('store/intake',{s:admin,body:{clientId:first.data.clientId,consent:true,vehicle:{plate:'ZZZ002',chassis:'OLD-CAR-123',brand:'Renault',model:'4',year:1984}}});eq(second.status,201,'old chassis without modern VIN');
for(const role of ['compras','bodega','contabilidad'])eq((await call('store/state',{s:roles[role]})).data.vehicles,[],'no CRM identifier leakage '+role);
eq((await call('store/vehicles',{s:admin,method:'PATCH',body:{id:v.id,version:1,consent:true,vehicle:{vin:'JTEBH3FJ70K123457'}}})).status,409,'cannot change history identity');
const updated=await call('store/vehicles',{s:roles.vendedor,method:'PATCH',body:{id:v.id,version:1,consent:true,vehicle:{engine:'Reviewed engine'}}});eq(updated.status,200,'vehicle edit');eq(updated.data.version,2,'increment version');eq((await call('store/vehicles',{s:admin,method:'PATCH',body:{id:v.id,version:1,consent:true,vehicle:{color:'Rojo'}}})).status,409,'stale edit conflict');
const addedVin=await call('store/vehicles',{s:admin,method:'PATCH',body:{id:second.data.vehicle.id,version:1,consent:true,vehicle:{vin:'JTEBH3FJ70K123457'}}});eq(addedVin.status,200,'may add a previously missing VIN after identification');eq(addedVin.data.chassis,'OLD-CAR-123','legacy chassis preserved');
const product=(await call('store/records',{s:admin,body:{kind:'products',data:{code:'FIXTURE-PAD-001',name:'Fixture pads',brand:'Fixture',category:'Frenos',location:'T-01',price:100000,cost:40000,tax:19,stock:0,min:1}}})).data;
const link={vehicleId:v.id,productId:product.id,system:'frenos',component:1,status:'candidate',source:'Fictional test catalogue',notes:'Test only',confirmed:false};
eq((await call('store/vehicle-parts?vehicleId='+v.id,{s:roles.vendedor})).status,403,'seller needs EPC grant');eq((await call('store/vehicle-parts',{s:roles.vendedor,body:link})).status,403,'map binding needs EPC grant');eq((await call('store/vehicle-parts',{s:admin,body:{...link,status:'reviewed'}})).status,400,'reviewed requires manual confirmation');eq((await call('store/vehicle-parts',{s:admin,body:{...link,source:''}})).status,400,'traceable source required');eq((await call('store/vehicle-parts',{s:admin,body:{...link,system:'fake'}})).status,400,'allowed system');eq((await call('store/vehicle-parts',{s:admin,body:{...link,component:5}})).status,400,'valid component');
const saved=await call('store/vehicle-parts',{s:admin,body:{...link,oemVerified:true,reference:'spoof'}});eq(saved.status,201,'persisted link');eq(saved.data.reference,product.code,'reference loaded from actual product');eq(saved.data.oemVerified,false,'OEM spoof ignored');eq(saved.data.status,'candidate','not automatically reviewed');eq((await call('store/vehicle-parts',{s:admin,body:link})).status,409,'duplicate link blocked');eq((await call('store/vehicle-parts?vehicleId='+v.id,{s:admin})).data.links.length,1,'links reload');eq((await call('store/vehicle-parts?vehicleId='+second.data.vehicle.id,{s:admin})).data.links.length,0,'VIN isolation');
await call('store/epc-access',{s:admin,body:{kind:'staff',email:'vendedor@example.invalid',enabled:true}});eq((await call('store/vehicle-parts?vehicleId='+v.id,{s:roles.vendedor})).status,200,'individual grant applied');
const reviewed=await call('store/vehicle-parts',{s:roles.vendedor,method:'PATCH',body:{...link,id:saved.data.id,version:1,status:'reviewed',confirmed:true}});eq(reviewed.status,200,'manual sourced review');eq(reviewed.data.oemVerified,false,'manual review not OEM feed');eq((await call('store/vehicle-parts',{s:admin,method:'PATCH',body:{...link,id:saved.data.id,version:1}})).status,409,'stale mapping conflict');eq((await call('store/vehicle-parts',{s:admin,method:'PATCH',body:{...link,id:saved.data.id,version:2,vehicleId:second.data.vehicle.id}})).status,400,'cannot move history to another vehicle');
const quote={clientId:first.data.clientId,vehicleId:v.id,items:[{productId:product.id,qty:1}],notes:'Fixture quote'};const quoted=await call('store/quotes',{s:roles.vendedor,body:quote});eq(quoted.status,201,'vehicle quotation');eq(quoted.data.vehicle.vin,v.vin,'snapshot vehicle VIN');eq(quoted.data.items[0].fulfillment,'sobre pedido','zero stock is under order');eq('cost' in quoted.data.items[0],false,'seller no cost');
const stranger=(await call('store/records',{s:admin,body:{kind:'clients',data:{...intake.client,name:'Other client',email:'other@example.invalid'}}})).data;eq((await call('store/quotes',{s:admin,body:{...quote,clientId:stranger.id}})).status,400,'cannot quote another clients vehicle');
const order=await call('store/convert',{s:admin,body:{source:quoted.data.id,type:'order'}});eq(order.data.vehicle.id,v.id,'order keeps vehicle');eq((await call('store/state',{s:roles.bodega})).data.documents[0].vehicle,undefined,'warehouse no VIN');
await call('store/epc-access',{s:admin,body:{kind:'staff',email:'vendedor@example.invalid',enabled:false}});eq((await call('store/vehicle-parts?vehicleId='+v.id,{s:roles.vendedor})).status,403,'revocation immediate');eq((await call('store/vehicles',{s:roles.vendedor})).status,200,'CRM without map still works');eq((await call('catalog')).data.products.length,0,'unpublished products stay private');
const backup=(await call('store/backup',{s:admin})).data;eq(backup.records.filter(r=>r.kind==='vehicles').length,2,'vehicle backup');eq(backup.records.filter(r=>r.kind==='fitments').length,1,'mapping backup');
const relog=session(await call('store/login',{body:{email:env.STORE_OWNER_EMAIL,password}}));eq((await call('store/vehicle-parts?vehicleId='+v.id,{s:relog})).data.links[0].status,'reviewed','persistent relogin');
const changedProduct=(await call('store/state',{s:admin})).data.products[0];eq((await call('store/product',{s:admin,method:'PATCH',body:{id:product.id,version:changedProduct.version,data:{code:'FIXTURE-PAD-NEW',published:false}}})).status,200,'catalogue reference changed');const staleLink=(await call('store/vehicle-parts?vehicleId='+v.id,{s:admin})).data.links[0];eq(staleLink.status,'candidate','changed code invalidates prior manual review');eq(staleLink.reference,'FIXTURE-PAD-NEW','map searches current product reference');eq(staleLink.previousReference,'FIXTURE-PAD-001','source reference trace retained');
console.log(JSON.stringify({passed:checks,flows:['atomic intake and consent','VIN/chassis validation and duplicates','CRM privacy and garage separation','individual EPC permissions and revocation','sourced per-vehicle reference mapping','optimistic editing','quotation ownership/snapshot','stock under order','backup and persistence']}));
